name: interval-test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: flake8 Testing (Syntax)
        run: flake8 . --exit-zero --max-line-length=127 # run flake8 test

      - name: Test Cadences (pytest)
        run: pytest test/test_cadences.py

      - name: Test Constants (pytest)
        run: pytest test/test_constants.py

      - name: Test Main Objs (pytest)
        run: pytest test/test_main_objs.py

      - name: Test Vis (pytest)
        run: pytest test/test_vis.py
        
      - name: Install poetry and "patch" the build
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self add poetry-bumpversion
          poetry version patch
          
      - name: Publish to Pypi
        if: github.ref == 'refs/heads/master'
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
          poetry publish --build

      - name: Checkout Code Again
        uses: actions/checkout@v3

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4



          
      # - name: Build and publish to PyPI
      #   env:
      #     TWINE_USERNAME: __token__  # Replace with your PyPI username or token
      #     TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # Add this token as a GitHub repository secret
        # run: |
        #   poetry build
        #   twine upload ./crim_intervals
