name: interval-test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install libxml2 and libxslt development packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev libxml-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: flake8 Testing (Syntax)
        run: flake8 . --exit-zero --max-line-length=127 # run flake8 test

      - name: Test Cadences (pytest)
        run: python -m unittest test.test_cadences

      - name: Test Constants (pytest)
        run: python -m unittest test.test_constants

      - name: Test Main Objs (pytest)
        run: python -m unittest test.test_main_objs

      - name: Test Vis (pytest)
        run: python -m unittest test.test_vis

      - name: Install poetry and "patch" the build
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self add poetry-bumpversion
          poetry version patch

      - name: Publish to Pypi (only if on Master)
        if: github.ref == 'refs/heads/master'
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
          poetry publish --build

      - name: Checkout code again
        uses: actions/checkout@v3

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
